{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{section show=$attribute.content.is_valid}
<script type="text/javascript" src="http://api.maps.yahoo.com/ajaxymap?v=2.0&appid={ezini('GISSettings','ApplicationID','gis.ini')}"></script>
{literal}
<style type="text/css">
#mapContainer {
    height: 300px;
    width: 300px;
    float: right;
}
</style>
<div id="mapContainer"></div>

<script type="text/javascript">
// Capture the user mouse-click and expand the SmartWindow
function onSmartWinEvent() {
     var words = "<b>Current location</b>";      marker.openSmartWindow(words);
}
  // Create a lat/lon object
  var myPoint = new YGeoPoint({/literal}{$attribute.content.latitude}{literal},{/literal}{$attribute.content.longitude}{literal});
  // Create a map object
  var map = new  YMap(document.getElementById('mapContainer'));
  // Add a pan control
  map.addPanControl();
  // Add a slider zoom control
  map.addZoomLong();
  // Display the map centered on a latitude and longitude
  map.drawZoomAndCenter(myPoint, 3);

  // Create a marker positioned at a lat/lon
	var marker = new YMarker(myPoint);
  // Add a label to the marker
	marker.addLabel("C");
	// Call onSmartWinEvent when the user clicks on the marker
YEvent.Capture(marker, EventsList.MouseClick, onSmartWinEvent);
// Display the marker
map.addOverlay(marker);

</script>
{/literal}
{/section}

{default attribute_base=ContentObjectAttribute}
<div class="block">
<label>{'Latitude'|i18n( 'extension/gis' )}:</label>
<input class="halfbox" type="text" name="{$attribute_base}_ezgis_latitude_{$attribute.id}" size="12" value="{section show=$attribute.content.is_valid}{$attribute.content.latitude}{/section}" />

<label>{'Longitude'|i18n( 'extension/gis' )}:</label>
<input class="halfbox" type="text" name="{$attribute_base}_ezgis_longitude_{$attribute.id}" size="12" value="{section show=$attribute.content.is_valid}{$attribute.content.longitude}{/section}" />

<label>{'Street'|i18n( 'extension/gis' )}:</label>
<input class="halfbox" type="text" name="{$attribute_base}_ezgis_street_{$attribute.id}" size="12" value="{section show=$attribute.content.is_valid}{$attribute.content.street}{/section}" />
<label>{'ZIP'|i18n( 'extension/gis' )}:</label>
<input class="halfbox" type="text" name="{$attribute_base}_ezgis_zip_{$attribute.id}" size="12" value="{section show=$attribute.content.is_valid}{$attribute.content.zip}{/section}" />
<label>{'City'|i18n( 'extension/gis' )}:</label>
<input class="halfbox" type="text" name="{$attribute_base}_ezgis_city_{$attribute.id}" size="12" value="{section show=$attribute.content.is_valid}{$attribute.content.city}{/section}" />
<label>{'State'|i18n( 'extension/gis' )}:</label>
<input class="halfbox" type="text" name="{$attribute_base}_ezgis_state_{$attribute.id}" size="12" value="{section show=$attribute.content.is_valid}{$attribute.content.state}{/section}" />
<label>{'Country'|i18n( 'extension/gis' )}:</label>
<input class="halfbox" type="text" name="{$attribute_base}_ezgis_country_{$attribute.id}" size="12" value="{section show=$attribute.content.is_valid}{$attribute.content.country}{/section}" />
<label>{'Update Location'|i18n( 'extension/gis' )}:</label>
<input class="button" name="{$attribute_base}_ezgis_update_{$attribute.id}" value="Update map" title="Resolve Information" type="checkbox">

    <input class="button" name="StoreButton" value="Update map" title="Resolve Information" type="submit">
    
<p>
<label>{'Use this link to find location based on an address'|i18n( 'extension/gis' )}:</label>
<a href="{ezini("GISSettings","GeocoderURL","gis.ini")}" target="_blank">{'Lookup'|i18n( 'extension/gis' )}</a>
</p>
</div>
{/default}
